git:
  paging:
    colorArg: always
    pager: delta --paging=never
customCommands:
  - key: 'C'
    command: 'cz c -- -S'
    description: 'use commitizen'
    context: files
    loadingText: 'opening commitizen'
    output: terminal
gui:
  showFileIcons: true
  nerdFontsVersion: "3"
  showIcons: true
