
## configs
[[session]]
name = "⚙️ dotfiles"
path = "~/dotfiles"

[[session]]
name = " neovim config"
path = "~/dotfiles/.config/nvim"

[[session]]
name = "✏️ obsidian work"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/work"
